# spring:
#  application:
#   name: manage-service
# #  config:
# #   activate:
# #    on-profile: dev

# spring:
#  profiles:
#     include:
#     - db  

# spring:
#  application:
#   name: manage-service
#  profiles:
#   active: dev
#    include: db

# spring:
#  profiles:
#   include: db

# spring:
#  application:
#   name: manage-service
#  activate:
#   on-profile: local
#  profiles:
#   include: db

# spring:
#  config:
#   activate:
#    on-profile: local
#  profiles:
#   include: 
#    -db

# spring:
#  config:
#   activate:
#    on-profile: dev
#  profiles:
#   include: db

spring:
  profiles:
    active: db
---

server:
  port: 8002  
   

--- 

# security 설정
spring:    
  security:
    oauth2:
     resourceserver:
        jwt:
          jwk-set-uri: http://192.168.1.54:8080/auth/realms/MSA/protocol/openid-connect/certs

#keycloak 설정      
keycloak:
  realm: MSA
  bearer-only: true
  ssl-required: external
  resource: spring-gateway-client
  auth-server-url: http://192.168.1.54:8080/auth
  credentials:
    secret: WEcACPUTWPfuhPrEz3bBaHcl7OLLmYX1
    

# 유레카 클라이언트 설정  
eureka:
  instance:
    instance-id: manage-microservice-instance # eureka에 등록되는 id 값
  client:
    register-with-eureka: true  # 유레카에 등록할지 여부.
    fetch-registry: true   # 유레카에서 조회할지 여부
    service-url:
     defaultZone: http://localhost:8761/eureka # 서비스를 등록할 서버 주소를 지정  #임시 : 도커를 위해 현민ip주소에 등록

# mybatis 연동 설정  
mybatis:
  mapper-locations: /mapper/**/*.xml
  type-aliases-package: com.dream.manage.dto
