# spring:
#   application:
#     name: manage-service
#   profiles:
#    active: qa

# spring :
#    config :
#      activate :
#        on-profile : qa

spring:
  config:
    activate:
      on-profile: manage-service
  profiles:
    include: qa
