# spring:
#   application:
#     name: manage-service
#   profiles:
#    active: qa

# spring :
#    config :
#      activate :
#        on-profile : qa

# spring:
#   application:
#     name: manage-service
#   config:
#     activate:
#       on-profile: qa
# #   profiles:
# #     include: qa
#   profiles:
#    active: qa

spring:
  application:
    name: manage-service
  profiles:
    group:
      "production": manage-service-qa
