spring:
  application:
    name: menu-service
    
# 유레카 클라이언트 설정  
eureka:
 instance:
   instance-id: menu-microservice-instance # eureka에 등록되는 id 값
 client:
   register-with-eureka: true  # 유레카에 등록할지 여부.
   fetch-registry: true   # 유레카에서 조회할지 여부
   service-url:
     defaultZone: http://127.0.0.1:8761/eureka 
