spring:
  application:
    name: menu-service
    
# 유레카 클라이언트 설정  
eureka:
 instance:
   instance-id: menu-microservice-instance # eureka에 등록되는 id 값
 client:
   register-with-eureka: true  # 유레카에 등록할지 여부.
   fetch-registry: true   # 유레카에서 조회할지 여부
   service-url:
     defaultZone: http://127.0.0.1:8761/eureka 
# ---
# spring:
#   devtools:
#      livereload:  #html, css, js 수정 시 새로고침 없이 바로 적용가능
#        enabled: true
#      restart:   # 재시작시 완전히 꺼졌다 다시키는 것보다 훨씬 빠르게 해줌.
#       enabled: true
